export const copy = {
  appName: "MaxShorts",
  loading: "Carregando…",
  unavailableTitle: "Clipe indisponível",
  unavailableBody: "Esse clipe não carregou. Pule para o próximo ou tente de novo.",
  retry: "Tentar de novo",
  skip: "Pular",
  paused: "Pausado",
  pause: "Pausa",
  pauseClip: "Pausar clipe",
  resumeClip: "Continuar clipe",
  mute: "Mudo",
  sound: "Som",
  soundOn: "Som ligado",
  enableSound: "Ativar som",
  disableSound: "Desativar som",
  like: "Curtir o clipe",
  unlike: "Remover curtida",
  prevClip: "Clipe anterior",
  nextClip: "Próximo clipe",
  chooseFeed: "Escolher feed",
  hintMobile: "Arrasta pra cima",
  hintDesktop: "↑ ↓ / espaço / M",
  counter: (current: number, total: number) => `${current}/${total}`,
  failedSkipToast: "Clipe falhou, pulando…",
  emptyTitle: "Nenhum clipe por aqui",
  emptyBody: "O feed ainda está vazio. Volte mais tarde — ou abra outro saco de peças.",
  fullscreen: "Tela cheia",
  exitFullscreen: "Sair da tela cheia",
  phoneLayout: "Tela do celular",
  tabs: {
    lego: "Tijolos",
    celular: "Celular",
    tech: "Produtos",
  },
  subtitles: {
    lego: "clips de tijolos",
    celular: "montando celular",
    tech: "lançamentos tech",
  },
} as const;
